//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""8180be9d-9e8f-4520-9b34-6fe273809ff1"",
            ""actions"": [
                {
                    ""name"": ""Draw"",
                    ""type"": ""Value"",
                    ""id"": ""03add1ce-e451-4256-9d1c-458d0e496335"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""IsDrawing"",
                    ""type"": ""Button"",
                    ""id"": ""7452fa12-faa5-466c-a921-78453d0a5976"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cast"",
                    ""type"": ""Button"",
                    ""id"": ""dfd01cf6-d174-485e-9391-e10bba762f7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseRuneLeft"",
                    ""type"": ""Button"",
                    ""id"": ""f2a715b1-2fda-4e21-b08b-f360d4df6628"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseRuneRight"",
                    ""type"": ""Button"",
                    ""id"": ""32a20d70-0369-4546-acbc-6132e622d8e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""94787778-87a4-4178-9976-1ab7126ef9d9"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Draw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""528ebb1c-0209-488a-8723-1e34f407391f"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsDrawing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19a2503d-b8d5-4a2a-bf5c-df9148dd4b68"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6408fa96-a0f7-4939-84f0-6b19ee3dfcc0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseRuneLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f34a1d1a-96eb-4792-9032-cfbbe09c8bb3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseRuneRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_Draw = m_Touch.FindAction("Draw", throwIfNotFound: true);
        m_Touch_IsDrawing = m_Touch.FindAction("IsDrawing", throwIfNotFound: true);
        m_Touch_Cast = m_Touch.FindAction("Cast", throwIfNotFound: true);
        m_Touch_ChooseRuneLeft = m_Touch.FindAction("ChooseRuneLeft", throwIfNotFound: true);
        m_Touch_ChooseRuneRight = m_Touch.FindAction("ChooseRuneRight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private List<ITouchActions> m_TouchActionsCallbackInterfaces = new List<ITouchActions>();
    private readonly InputAction m_Touch_Draw;
    private readonly InputAction m_Touch_IsDrawing;
    private readonly InputAction m_Touch_Cast;
    private readonly InputAction m_Touch_ChooseRuneLeft;
    private readonly InputAction m_Touch_ChooseRuneRight;
    public struct TouchActions
    {
        private @Controls m_Wrapper;
        public TouchActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Draw => m_Wrapper.m_Touch_Draw;
        public InputAction @IsDrawing => m_Wrapper.m_Touch_IsDrawing;
        public InputAction @Cast => m_Wrapper.m_Touch_Cast;
        public InputAction @ChooseRuneLeft => m_Wrapper.m_Touch_ChooseRuneLeft;
        public InputAction @ChooseRuneRight => m_Wrapper.m_Touch_ChooseRuneRight;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void AddCallbacks(ITouchActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchActionsCallbackInterfaces.Add(instance);
            @Draw.started += instance.OnDraw;
            @Draw.performed += instance.OnDraw;
            @Draw.canceled += instance.OnDraw;
            @IsDrawing.started += instance.OnIsDrawing;
            @IsDrawing.performed += instance.OnIsDrawing;
            @IsDrawing.canceled += instance.OnIsDrawing;
            @Cast.started += instance.OnCast;
            @Cast.performed += instance.OnCast;
            @Cast.canceled += instance.OnCast;
            @ChooseRuneLeft.started += instance.OnChooseRuneLeft;
            @ChooseRuneLeft.performed += instance.OnChooseRuneLeft;
            @ChooseRuneLeft.canceled += instance.OnChooseRuneLeft;
            @ChooseRuneRight.started += instance.OnChooseRuneRight;
            @ChooseRuneRight.performed += instance.OnChooseRuneRight;
            @ChooseRuneRight.canceled += instance.OnChooseRuneRight;
        }

        private void UnregisterCallbacks(ITouchActions instance)
        {
            @Draw.started -= instance.OnDraw;
            @Draw.performed -= instance.OnDraw;
            @Draw.canceled -= instance.OnDraw;
            @IsDrawing.started -= instance.OnIsDrawing;
            @IsDrawing.performed -= instance.OnIsDrawing;
            @IsDrawing.canceled -= instance.OnIsDrawing;
            @Cast.started -= instance.OnCast;
            @Cast.performed -= instance.OnCast;
            @Cast.canceled -= instance.OnCast;
            @ChooseRuneLeft.started -= instance.OnChooseRuneLeft;
            @ChooseRuneLeft.performed -= instance.OnChooseRuneLeft;
            @ChooseRuneLeft.canceled -= instance.OnChooseRuneLeft;
            @ChooseRuneRight.started -= instance.OnChooseRuneRight;
            @ChooseRuneRight.performed -= instance.OnChooseRuneRight;
            @ChooseRuneRight.canceled -= instance.OnChooseRuneRight;
        }

        public void RemoveCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITouchActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnDraw(InputAction.CallbackContext context);
        void OnIsDrawing(InputAction.CallbackContext context);
        void OnCast(InputAction.CallbackContext context);
        void OnChooseRuneLeft(InputAction.CallbackContext context);
        void OnChooseRuneRight(InputAction.CallbackContext context);
    }
}
